# Roles kubernetes worker node

- name: Copy Kubernetes Repository
  shell: |
         cat <<EOF > /etc/yum.repos.d/kubernetes.repo
         [kubernetes]
         name=Kubernetes
         baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
         enabled=1
         gpgcheck=1
         repo_gpgcheck=1
         gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
         EOF

- name: install kubelet
  yum:
    name: kubelet
    state: installed

- name: install kubeadm
  yum:
    name: kubeadm
    state: installed

- name: install kubectl
  yum:
    name: kubectl
    state: installed

- name: enable kubectl
  systemd:
    name: kubectl
    state: started
    enabled: yes

- name: Start service kubelet
  service:
    name: kubelet
    state: started

- name: Set Hostname Worker Nodes
  shell: sudo hostnamectl set-hostname worker-node1

- name: Template Resolve the hostname master nodes
  template:
    src: /roles/kubernetesMaster/templates/hostname.j2
    dest: /etc/hosts

- name: Configure Firewall
  firewalld:
    port: "{{ item }}"
    permanent: yes
    state: enabled
  with_items:
     - 6443/tcp
     - 2379-2380/tcp
     - 10250/tcp
     - 10251/tcp
     - 10252/tcp
     - 10255/tcp

- name: Update Iptables Settings
  shell: |
         cat <<EOF > /etc/sysctl.d/k8s.conf
         net.bridge.bridge-nf-call-ip6tables = 1
         net.bridge.bridge-nf-call-iptables = 1
         EOF
         sysctl --system

- name: Disable SELinux
  shell: sudo setenforce 0

- name: Disable SELinux
  shell: sudo sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config

- name: Disable SWAP
  shell: sudo sed -i '/swap/d' /etc/fstab

- name: Disable SWAP
  shell: sudo swapoff -a
